name: xfin
description: "A personal finance tracker."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Drift dependencies
  drift: ^2.19.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0
  sqflite: ^2.3.3+1
  drift_sqflite: ^2.0.1

  liquid_navbar: ^2.0.4
  share_plus: ^12.0.1
  file_saver: ^0.3.1
  flutter_file_saver: ^0.9.0
  file_selector: ^1.1.0
  file_picker: ^10.3.7
  permission_handler: ^12.0.1
  open_filex: ^4.5.1
  provider: ^6.1.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  oktoast: ^3.4.0
  fluttertoast: ^9.0.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  csv: ^5.0.0
  liquid_glass_renderer: ^0.2.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Drift dev dependency
  drift_dev: ^2.19.0
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0

  # Testing dependencies
  test: ^1.25.2
  sqlite3: ^2.4.4 # For in-memory testing
  remove_from_coverage: ^2.0.0
  test_reporter: ^1.3.0
  mockito: ^5.4.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
